---
- name: restart ipsec
  service:
    name: strongswan
    state: restarted

- name: reload ipsec
  command: ipsec reload

- name: save iptables
  command: netfilter-persistent save
  listen: persist iptables

- name: reload iptables
  command: netfilter-persistent reload
  listen: persist iptables
